linters:
    disable-all: true
    enable:
      - bodyclose
      - deadcode
      - depguard
      - dogsled
      - dupl
      - errcheck
      - gocognit
      - goconst
      - gocritic
      - gocyclo
      - gofmt
      - goimports
      - golint
      - gosec
      - gosimple
      - govet
      - ineffassign
      - interfacer
      - lll
      - maligned
      - misspell
      - nakedret
      - prealloc
      - scopelint
      - staticcheck
      - structcheck
      - typecheck
      - unconvert
      - unparam
      - unused
      - varcheck
      - whitespace
  
  linters-settings:
    lll:
      line-length: 140
  issues:
    exclude-use-default: false
  run:
    timeout: 3m
  service:
    golangci-lint-version: 1.20.x
  
  linters:
    disable: