name: golangci-lint
on: pull_request

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions-contrib/golangci-lint@v1
          with:
          # golangci-lint docker release tag
          golangci_lint_version: # optional, default is v1.23