name: Quality checks
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout
    - uses: actions-contrib/golangci-lint@v1
      env:
        GO111MODULE: "on"