name: Quality checks
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1
        env:
          GO111MODULE: "on"
          GOFLAGS: "-mod=vendor"